#!/bin/bash
# Set the MAC address of eth0, the Edison-Ethernet block. This script
# is intended to be placed in /etc/network/if-pre-up.d/ with +x perm.

MAC_FILE="/factory/mac"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

# This will set eth0 while the system is working on lo
if [ ! "$IFACE" == "lo" ];
then
    exit 0 
fi

# Only do the work if eth0 is an interface and the MAC_FILE exists
ifconfig eth0 > /dev/null
if [[ $? -eq 0 && -f $MAC_FILE ]];
then
   ETH0=$(cat $MAC_FILE)

   if [[ "$ETH0" =~ ^([0-9A-Fa-f]{2}[:-]){5}([0-9a-fA-F]{2})$ ]]; then
      echo
      echo -e "[${GREEN} ok ${NC}] Setting eth0 MAC to $ETH0"
      macchanger -m $ETH0 eth0 > /dev/null
   else
      DEF_ETH0=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
      echo
      echo -e "[${RED}fail${NC}] Invalid MAC address: $ETH0 [Try using the changemac command]"
      echo "       Using default MAC for eth0: $DEF_ETH0"
   fi
fi
